<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Requestum\ApiBundle\Filter\Handler\SearchHandler;
use Requestum\ApiBundle\Repository\ApiRepositoryTrait;
use Requestum\ApiBundle\Repository\FilterableRepositoryInterface;

use RQ\ContextBundle\Filter\Handler\ContextHandler;
use Requestum\ApiBundle\Filter\Handler\OrderHandler;
/**
 * HierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HierarchyRepository extends EntityRepository implements FilterableRepositoryInterface
{
    use ApiRepositoryTrait;

    /**
     * @inheritdoc
     */
    protected function createHandlers()
    {
        return [
            new ContextHandler(),
            new OrderHandler(),
        ];
    }

    /**
     * @return bool
     */
    protected function isUseOrderHandler()
    {
        return true;
    }

    public function findByParentIdOrdered($parentId)
    {
        $qb = $this->createQueryBuilder('h')
            ->andWhere('h.parentId = :parentId')
            ->setParameter('parentId', $parentId)
            ->orderBy('h.position', 'ASC')
            ->getQuery();

        return $qb->execute();
    }

}
